app/urls.py
from django.urls import path
from .views import HomeView
from . import views

app_name = 'app'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('list/', views.list_ports, name='list')
]

mobilink/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('app/',include('app.urls')),
    path('',views.home,name='home'),
]

app/models.py
from django.db import models

# Create your models here.
class SerialPorts(models.Model):
    #first_name = models.CharField(max_length=30)
    
    #def __str__(self):
    #    return f"{self.first_name} {self.last_name} teaches {self.subject}"
    pass 

app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from . import models
from serial.tools.list_ports import comports


# Create your views here.
class HomeView(TemplateView):
    template_name = 'app/home.html'


def list_ports(request):
    ports = []
    for n, (port, desc, hid) in enumerate(sorted(comports()), 1):
        # sys.stderr.write('{:2}: {:20} {!r}\n'.format(n, port, desc))
        if 'NULL' not in port:
            ports.append(port)

    context = {'all_ports': ports}
    return render(request, 'app/list.html', context=context)

mobilink/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
#def index(request):
#    return HttpResponse('hello')
def home(request):
    return render(request,'app/home.html')

app/templates/app/home.html
{% extends "base.html" %}

{% block content %}
<h1>Home Page</h1>

{% endblock content %}

app/templates/app/list.html
{% extends "base.html" %}

{% block content %}

<h4>IDD Interface Port:</h4>
<select class="form-select" aria-label="Default select example" name="SELECTED_COM">
    <option selected>Select COM port</option>
    {% for port in all_ports %}
    <option value={{port.id}}>{{port}}</option>
    {% endfor %}
</select>

{% endblock content %}

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'app/bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'app/bootstrap/js/bootstrap.min.js' %}"></script>
    <title>Mobius Link</title>
</head>
<body>

    <!-- NAVBAR-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/"><img src="{% static 'app/logo2_blue.png' %}" alt='logo' width="70" height="50">Mobi-Tech</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'app:list' %}">LIST</a>
                <a class="nav-item nav-link" href="">ADD</a>
                <a class="nav-item nav-link" href="">DELETE</a>
            </div>
        </div>
      </nav>

    {% block content %}   
    {% endblock %}

</body>
</html>